// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKR7IpMuiYmaXlDeXlm4prHrRxdhfdvg',
    appId: '1:549593533024:web:382f587ee9525754fe5105',
    messagingSenderId: '549593533024',
    projectId: 'rtc-app-f96fd',
    authDomain: 'rtc-app-f96fd.firebaseapp.com',
    storageBucket: 'rtc-app-f96fd.appspot.com',
    measurementId: 'G-WXESFTWK07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB39CIqliGw_zgppdPXHwR93eLGp2uWd5k',
    appId: '1:549593533024:android:e0f71e90b0bc0c84fe5105',
    messagingSenderId: '549593533024',
    projectId: 'rtc-app-f96fd',
    storageBucket: 'rtc-app-f96fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKWihynwEoS5eDvG_SeWVIPl6_WLxGgRE',
    appId: '1:549593533024:ios:e1acdd188ab40cadfe5105',
    messagingSenderId: '549593533024',
    projectId: 'rtc-app-f96fd',
    storageBucket: 'rtc-app-f96fd.appspot.com',
    iosClientId: '549593533024-5tvu88k08gnq6d0maldpbcotobu0joj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rtcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKWihynwEoS5eDvG_SeWVIPl6_WLxGgRE',
    appId: '1:549593533024:ios:e1acdd188ab40cadfe5105',
    messagingSenderId: '549593533024',
    projectId: 'rtc-app-f96fd',
    storageBucket: 'rtc-app-f96fd.appspot.com',
    iosClientId: '549593533024-5tvu88k08gnq6d0maldpbcotobu0joj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rtcApp',
  );
}
